### PR TITLE
Async Support

### PR DESCRIPTION
**Pull request by mdm9300404**
I added async support for most of this library

Also replaced .png with .jpg as outlined in the pull request [here](https://github.com/FireHead90544/craiyon.py/pull/2)

This new version requires some extra dependencies: aiohttp, aiofiles, and aiopath

Sorry for all the commits lol, I was just iterating a bit

This is literally my first **public** pull request so if I screwed something up lemme know please thanks

### CODE REVIEW

**Comment by FireHead90544** [comment]
Great job, thankyou :)
Just update the metadata, i.e version to `0.2.0` in `craiyon/__init__.py` and `README.md`. Also add yourself in the contributors/author's list in `README.md`. I'll be merging the PR shortly after that since I'll have to push the changes to PyPI manually :')

**Comment by mdm9300404** [comment]
> Great job, thankyou :) Just update the metadata, i.e version to `0.2.0` in `craiyon/__init__.py` and `README.md`. Also add yourself in the contributors/author's list in `README.md`. I'll be merging the PR shortly after that since I'll have to push the changes to PyPI manually :')

Is that good? I've never made a package on PyPI before, just used packages from there lol

**Comment by FireHead90544** [comment]
That's pretty neat, I'll be merging it soon :)

**Comment by bensonchow123** [comment]
Can't wait for this to merge so i can use it in my discord bot

**Comment by FireHead90544** [comment]
> Can't wait for this to merge so i can use it in my discord bot

I totally forgot about merging it, I'll be doing it most probably by today night. Sorry for the delay :')

**Comment by bensonchow123** [comment]
In crayaion.py in both
`return GeneratedImages(await resp.json())`
`return GeneratedImages(resp.json())`
It should be 
`resp.json()["images"]`
whoever made the pull request forgot about it

**Comment by mdm9300404** [comment]
> In crayaion.py in both `return GeneratedImages(await resp.json())` `return GeneratedImages(resp.json())` It should be `resp.json()["images"]` whoever made the pull request forgot about it

I moved that to lines #17 and #28 in the file templates.py, ...though I now see why it was like that in the first place. I'm gonna fix that, hang on.

Thanks for letting me know!

**Comment by FireHead90544** [comment]
I assume the code is working fine as expected (since I am currently unable to try it out myself). So, I am merging it for now. Please create an issue if you face any errors.

**Comment by FireHead90544** [comment]
Forgot to mention, I'll be updating the version on PyPI at some later point of time. So until then, update your site-package by using:
`pip install git+https://github.com/FireHead90544/craiyon.py.git`

**Pull request merged**
