### PR TITLE
changed output 'jpg' file extension to 'webp'

### PR DESCRIPTION
**Pull request by wordboxx**
craiyon changed the file format again.

### CODE REVIEW

**Comment by mdm9300404** [comment]
Please correct me if I am wrong (I very well could be), but I believe this only applies to Craiyon's v2 model

2.0 is https://api.craiyon.com/draw

Previously it was https://backend.craiyon.com/generate, which this library currently uses


2.0 also responds with direct image URLs this time, via https://img.craiyon.com

**Comment by FireHead90544** [comment]
> Please correct me if I am wrong (I very well could be), but I believe this only applies to Craiyon's v2 model
> 
> 2.0 is https://api.craiyon.com/draw
> 
> Previously it was https://backend.craiyon.com/generate, which this library currently uses

Yeah, as @mdm9300404 mentioned, the library uses v1 of the Craiyon backend and it doesn't have the extension changed. The new v2 indeed generate images in `.webp` format. 

I'll be adding the v2 server classes pretty soon to this library. If anyone else would like to implement that, feel free to do so, just make sure to change to properly differentiate the classes through V1 and V2 and as the v2 model is much more better and faster, what's your thoughts on changing the Craiyon class to v2 itself and changing the current one to CraiyonV1 for backward compatibility?

**Comment by mdm9300404** [comment]
> what's your thoughts on changing the Craiyon class to v2 itself and changing the current one to CraiyonV1 for backward compatibility?

Got a little confused reading this. Could you elaborate more?

**Comment by FireHead90544** [comment]
> > what's your thoughts on changing the Craiyon class to v2 itself and changing the current one to CraiyonV1 for backward compatibility?
> 
> Got a little confused reading this. Could you elaborate more?

Sure, I just suggested that the current `Craiyon` class be renamed to `CraiyonV1` and the new v2 class, which is yet to be implemented in the wrapper be named `CraiyonV2` along with it being accessible with the name `Craiyon` as well, i.e if you want to use the v1 model, you needa explicitly mention `CraiyonV1` but the default model will be v2 which can be accessed through `Craiyon` or `CraiyonV2` 😅

Open to other suggestions though :)

**Comment by mdm9300404** [comment]
> > > what's your thoughts on changing the Craiyon class to v2 itself and changing the current one to CraiyonV1 for backward compatibility?
> > 
> > 
> > Got a little confused reading this. Could you elaborate more?
> 
> Sure, I just suggested that the current `Craiyon` class be renamed to `CraiyonV1` and the new v2 class, which is yet to be implemented in the wrapper be named `CraiyonV2` along with it being accessible with the name `Craiyon` as well, i.e if you want to use the v1 model, you needa explicitly mention `CraiyonV1` but the default model will be v2 which can be accessed through `Craiyon` or `CraiyonV2` 😅
> 
> Open to other suggestions though :)

Ah alright, sounds like a pretty good idea. If I decide to make a PR I'll probably just name the V2 class `Craiyon` instead of `CraiyonV2`

I already have V2 working in one of my Discord bots so I am considering maybe opening a PR soon, though no guarantees.

**Comment by FireHead90544** [comment]
> > > > what's your thoughts on changing the Craiyon class to v2 itself and changing the current one to CraiyonV1 for backward compatibility?
> > > 
> > > 
> > > Got a little confused reading this. Could you elaborate more?
> > 
> > 
> > Sure, I just suggested that the current `Craiyon` class be renamed to `CraiyonV1` and the new v2 class, which is yet to be implemented in the wrapper be named `CraiyonV2` along with it being accessible with the name `Craiyon` as well, i.e if you want to use the v1 model, you needa explicitly mention `CraiyonV1` but the default model will be v2 which can be accessed through `Craiyon` or `CraiyonV2` 😅
> > Open to other suggestions though :)
> 
> Ah alright, sounds like a pretty good idea. If I decide to make a PR I'll probably just name the V2 class `Craiyon` instead of `CraiyonV2`
> 
> I already have V2 working in one of my Discord bots so I am considering maybe opening a PR soon, though no guarantees.

That's the spirit, thankyou 🫡

**Comment by FireHead90544** [comment]
This is resolved in [v0.3.0](https://pypi.org/project/craiyon.py/0.3.0/) Please refer to [this PR](https://github.com/FireHead90544/craiyon.py/pull/8).

**Pull request closed without merging**
